// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Database;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241020033303_RenameFieldNames")]
    partial class RenameFieldNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProductId");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ProductCategory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ProductName");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProductPrice");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "DogFood",
                            Name = "Dry Dog Food",
                            Price = 50m
                        },
                        new
                        {
                            Id = 2L,
                            Category = "DogFood",
                            Name = "Wet Dog Food",
                            Price = 35m
                        },
                        new
                        {
                            Id = 3L,
                            Category = "DogFood",
                            Name = "Dog Treats",
                            Price = 10m
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Toys",
                            Name = "Chew Toy",
                            Price = 15m
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Toys",
                            Name = "Fetch Ball",
                            Price = 8m
                        },
                        new
                        {
                            Id = 6L,
                            Category = "CollarsAndLeashes",
                            Name = "Dog Collar",
                            Price = 12m
                        },
                        new
                        {
                            Id = 7L,
                            Category = "CollarsAndLeashes",
                            Name = "Dog Leash",
                            Price = 20m
                        },
                        new
                        {
                            Id = 8L,
                            Category = "GroomingAndHygiene",
                            Name = "Dog Shampoo",
                            Price = 10m
                        },
                        new
                        {
                            Id = 9L,
                            Category = "GroomingAndHygiene",
                            Name = "Dog Brush",
                            Price = 7m
                        },
                        new
                        {
                            Id = 10L,
                            Category = "Beds",
                            Name = "Comfort Dog Bed",
                            Price = 80m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
