// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Database;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241019215000_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductCategory = "DogFood",
                            ProductName = "Dry Dog Food",
                            ProductPrice = 50m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductCategory = "DogFood",
                            ProductName = "Wet Dog Food",
                            ProductPrice = 35m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductCategory = "DogFood",
                            ProductName = "Dog Treats",
                            ProductPrice = 10m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductCategory = "Beds",
                            ProductName = "Chew Toy",
                            ProductPrice = 15m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductCategory = "Beds",
                            ProductName = "Fetch Ball",
                            ProductPrice = 8m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductCategory = "CollarsAndLeashes",
                            ProductName = "Dog Collar",
                            ProductPrice = 12m
                        },
                        new
                        {
                            ProductId = 7,
                            ProductCategory = "CollarsAndLeashes",
                            ProductName = "Dog Leash",
                            ProductPrice = 20m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductCategory = "GroomingAndHygiene",
                            ProductName = "Dog Shampoo",
                            ProductPrice = 10m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductCategory = "GroomingAndHygiene",
                            ProductName = "Dog Brush",
                            ProductPrice = 7m
                        },
                        new
                        {
                            ProductId = 10,
                            ProductCategory = "Beds",
                            ProductName = "Comfort Dog Bed",
                            ProductPrice = 80m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
