DO
$$
    BEGIN
        CREATE TABLE IF NOT EXISTS suppliers
        (
            supplier_id         BIGINT GENERATED BY DEFAULT AS IDENTITY
                CONSTRAINT "PK_Suppliers" PRIMARY KEY,
            supplier_firstname  VARCHAR(255) NOT NULL,
            supplier_lastname   VARCHAR(255) NOT NULL,
            supplier_email      VARCHAR(255),
            supplier_created_at TIMESTAMPTZ  NOT NULL
        );
    END
$$
