DO
$$
    BEGIN
        ALTER TABLE addresses ADD COLUMN user_id BIGINT;

        ALTER TABLE phone_numbers ADD COLUMN user_id BIGINT;

        CREATE TABLE IF NOT EXISTS users
        (
            user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY
                CONSTRAINT "PK_Users" PRIMARY KEY,
            user_username      VARCHAR(255) NOT NULL UNIQUE,
            user_password_hash VARCHAR(255) NOT NULL,
            user_email         VARCHAR(255) NOT NULL UNIQUE,
            user_firstname     VARCHAR(255) NOT NULL,
            user_lastname      VARCHAR(255) NOT NULL,
            user_created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            user_last_login    TIMESTAMPTZ
        );
    END
$$;
